### PR TITLE
feat: adds models for video engagement reports (FC-0024)

### PR DESCRIPTION
**Pull request by SoryRawyer**
Adds two new models for issue #3 :
- `video_plays`: contains a record for each time a learner played a video. Can be used to generate reports of total plays and unique watchers
- `transcript_usage`: contains a record for each time a transcript or closed caption was enabled. Can be used to generate reports for total transcription/caption usage as well as the number of unique learners who enabled transcription/closed captioning

For each model, `org`, `course_id`, and `video_id` are available as dimensions.

**Question for reviewers:** is there a more robust way of deriving a video ID from the `object_id`? This approach works for test data but uses a relatively naive approach and may not accurately capture the video ID from different environments.

**Note:** this PR does not define the metrics available from these tables as they also need to be defined in Superset. I have Superset datasets (and an example chart) for each model and can export and share them if that's helpful.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by bmtcril** [comment]
Is this going to need to be refactored after the mv changes?

**Comment by SoryRawyer** [comment]
It is, just a little bit. I'll update the PR to reflect the MV changes.

**Comment by SoryRawyer** [comment]
It doesn't look like my rebase worked as I'd expected, so I'm just going to close this PR and open a new one with the same changes.

**Comment by openedx-webhooks** [comment]
@SoryRawyer Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/aspects-dbt&entry.867055334=https://github.com/openedx/aspects-dbt/pull/6&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2023-06-21+19:34&entry.1917517419=2023-06-25+13:38&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
