### PR TITLE
feat: add dbt documentation

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

This PR creates a GitHub workflow to generate the DBT docs and publish it to GitHub pages.

The destination branch is `gh-pages` and the documentation is generated on every push a main.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Ian2012** [comment]
cc @SoryRawyer

**Comment by bmtcril** [comment]
This won't work because the static content needs to be served out of either the site root or the /docs/ directory. I think we can use this as a template: https://medium.com/dbt-local-taiwan/host-dbt-documentation-site-with-github-pages-in-5-minutes-7b80e8b62feb 

If you set up a `gh-pages` branch with the contents of the `target` dir like in that post I can create the static site and we can work on setting up an action to automatically push to that branch when something merges to main.

**Review by bmtcril — APPROVED** [review]
Looks great, can you just update the PR description to match current reality before merging?

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/aspects-dbt&entry.867055334=https://github.com/openedx/aspects-dbt/pull/31&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-10-11+20:16&entry.1917517419=2023-10-12+17:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
