### PR TITLE
feat: add models for navigation events (FC-0033)

### PR DESCRIPTION
**Pull request by SoryRawyer**
This PR adds a materialized view for navigation events and an accompanying view that enriches the MV with course and block metadata.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]

**Comment by bmtcril** [comment]
I approved, but can you add docs for these as well, please?

**Comment by SoryRawyer** [comment]
Ah yes, sorry for the oversight. Also, since there could be either sequential or vertical blocks in these models, does it make sense to leave the fields `block_id` and `block_name` as-is? I wasn't sure what a more descriptive name would be.

**Comment by bmtcril** [comment]
Pretty sure this is good since I think we primarily use `block_name_with_location`, but let me know if I'm missing something

**Comment by SoryRawyer** [comment]
I can't think of anything. Thanks!

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/aspects-dbt&entry.867055334=https://github.com/openedx/aspects-dbt/pull/40&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2024-01-12+17:12&entry.1917517419=2024-01-12+21:20&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bmtcril** [comment]
Released as `v3.2.0`

**Pull request merged**
